# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91a82aa08816d470b77550bf46b671bcc5df0b8d1064e3b6420a2cee111041c37ab76a0774fa90765f46fad34aa77ccd2dc21ef3e725ff149c6298e8f5f8765f

test:
  secret_key_base: d9b0cc6db130e92faa6a7e024442302e17f3d3c5c87e90b58370e4d7594744c602c3cb688ad3debe273d9afd5760ba45a065c67714a8758e026ae4cb29ce7ae4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
